# Generated by Django 6.0.1 on 2026-01-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='List of options for MCQ. Example: ["Option A", "Option B"]', null=True),
        ),
    ]
